version: "3"
services:
    webapp:
        build:
            context: ./frontend/
            dockerfile: ./Dockerfile
        ports:
            - "8081:80" #Levi or Alan, change this to xx:80 if port 8080 is occupied on your PC
        networks:
            - default
        restart: always
    json-server:
        build:
            context: ./backend/
            dockerfile: ./Dockerfile
        ports:
            - "3000:80"
        networks:
            - default
        restart: always
    socket-server:
        build:
            context: ./backend/
            dockerfile: ./Dockerfile_Sockets
        ports:
            - "3001:80"
        networks:
            - default
        restart: always